[project]
name = "lemma"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.50",
    "requests>=2.32.5",
]

[project.scripts]
lemma = "lemma.main:main"
